name: bikeweather

on:
  workflow_dispatch:

  schedule:
    # 07:00 Amsterdam:
    # 05:00 UTC during summer time
    # 06:00 UTC during winter time
    - cron: "0 5,6 * * *"

    # 15:00 Amsterdam:
    # 13:00 UTC during summer time
    # 14:00 UTC during winter time
    - cron: "0 13,14 * * *"

jobs:
  bikeweather:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run bike weather
        env:
          KNMI_API_KEY: ${{ secrets.KNMI_OPEN_DATA_API }}
          NTFY_TOPIC: ${{ secrets.NTFY_TOPIC }}
        run: python bikeweather.py
