name: bikeweather

on:
  workflow_dispatch:

jobs:
  fietsweer:
    runs-on: ubuntu-latest

    steps:
      - name: Code ophalen
        uses: actions/checkout@v4

      - name: Python installeren
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Packages installeren
        run: pip install -r requirements.txt

      - name: Script uitvoeren
        run: python bikeweather.py
